spring:
  application:
    name: Inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

