apiVersion: v1
kind: Secret
metadata:
  name: procurement-db-secret
  namespace: erp-microservices
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy # "myuser" base64 encoded
  POSTGRES_PASSWORD: c2VjcmV0 # "secret" base64 encoded

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: procurement-db-pvc
  namespace: erp-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: procurement-db-statefulset
  namespace: erp-microservices
spec:
  serviceName: "procurement-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: procurement-db
  template:
    metadata:
      labels:
        app: procurement-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: procurement-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: procurement-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: procurement-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: procurement-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard

---
apiVersion: v1
kind: Service
metadata:
  name: procurement-db-service
  namespace: erp-microservices
spec:
  ports:
    - port: 5432
      targetPort: postgresql
  selector:
    app: procurement-db
  type: ClusterIP
